### ISSUE TITLE
design/study sketch

### ISSUE THREAD

**Issue by the-razz** [Real-John-Cheung/AlternativeCCTV#2]
I guess we both need come up with our own ideas and then see later what we can make from them

**Comment by the-razz** [comment]
![installation sketch](https://user-images.githubusercontent.com/76756583/150178617-7ddab27a-6f8d-4203-bacf-0ec82eea9e82.jpg)

**Comment by Real-John-Cheung** [comment]
![14AD4050-7BA3-4DED-BDD9-9D08F36EBE61](https://user-images.githubusercontent.com/61215358/150630385-79c18d2a-3d9b-4707-9b48-959e602d0506.png)

**Comment by Real-John-Cheung** [comment]
Sketches moved to wordpress site
